-- 결과 페이지 확인용 샘플 데이터
INSERT INTO users (type) VALUES ('member');
INSERT INTO kind (kind_name, kind_text) VALUES ('성향1','성향1의 설명');
INSERT INTO kind (kind_name, kind_text) VALUES ('성향2','성향2의 설명');
INSERT INTO kind (kind_name, kind_text) VALUES ('성향3','성향3의 설명');
INSERT INTO user_kind (user_id, kind_id) VALUES (1, 1);
insert into section (section_name) VALUES ('섹션1');
insert into section (section_name) VALUES ('섹션2');
insert into section (section_name) VALUES ('섹션3');
insert into question (question_text, section_id) VALUES ('질문1', 1);
insert into question (question_text, section_id) VALUES ('질문2', 1);
insert into question (question_text, section_id) VALUES ('질문3', 1);
insert into question (question_text, section_id) VALUES ('질문4', 2);
insert into question (question_text, section_id) VALUES ('질문5', 2);
insert into question (question_text, section_id) VALUES ('질문6', 2);
insert into question (question_text, section_id) VALUES ('질문7', 3);
insert into question (question_text, section_id) VALUES ('질문8', 3);
insert into question (question_text, section_id) VALUES ('질문9', 3);
insert into answer (question_id, section_id, answer_text, score) VALUES (1, 1, '답변1', 1);
insert into answer (question_id, section_id, answer_text, score) VALUES (1, 1, '답변2', 2);
insert into answer (question_id, section_id, answer_text, score) VALUES (1, 1, '답변3', 3);
insert into answer (question_id, section_id, answer_text, score) VALUES (1, 1, '답변4', 4);
insert into answer (question_id, section_id, answer_text, score) VALUES (2, 1, '답변1', 1);
insert into answer (question_id, section_id, answer_text, score) VALUES (2, 1, '답변2', 2);
insert into answer (question_id, section_id, answer_text, score) VALUES (2, 1, '답변3', 3);
insert into answer (question_id, section_id, answer_text, score) VALUES (2, 1, '답변4', 4);
insert into answer (question_id, section_id, answer_text, score) VALUES (3, 1, '답변1', 1);
insert into answer (question_id, section_id, answer_text, score) VALUES (3, 1, '답변2', 2);
insert into answer (question_id, section_id, answer_text, score) VALUES (3, 1, '답변3', 3);
insert into answer (question_id, section_id, answer_text, score) VALUES (3, 1, '답변4', 4);
insert into answer (question_id, section_id, answer_text, score) VALUES (4, 2, '답변1', 1);
insert into answer (question_id, section_id, answer_text, score) VALUES (4, 2, '답변2', 2);
insert into answer (question_id, section_id, answer_text, score) VALUES (4, 2, '답변3', 3);
insert into answer (question_id, section_id, answer_text, score) VALUES (4, 2, '답변4', 4);
insert into answer (question_id, section_id, answer_text, score) VALUES (5, 2, '답변1', 1);
insert into answer (question_id, section_id, answer_text, score) VALUES (5, 2, '답변2', 2);
insert into answer (question_id, section_id, answer_text, score) VALUES (5, 2, '답변3', 3);
insert into answer (question_id, section_id, answer_text, score) VALUES (5, 2, '답변4', 4);
insert into answer (question_id, section_id, answer_text, score) VALUES (6, 2, '답변1', 1);
insert into answer (question_id, section_id, answer_text, score) VALUES (6, 2, '답변2', 2);
insert into answer (question_id, section_id, answer_text, score) VALUES (6, 2, '답변3', 3);
insert into answer (question_id, section_id, answer_text, score) VALUES (6, 2, '답변4', 4);
insert into answer (question_id, section_id, answer_text, score) VALUES (7, 3, '답변1', 1);
insert into answer (question_id, section_id, answer_text, score) VALUES (7, 3, '답변2', 2);
insert into answer (question_id, section_id, answer_text, score) VALUES (7, 3, '답변3', 3);
insert into answer (question_id, section_id, answer_text, score) VALUES (7, 3, '답변4', 4);
insert into answer (question_id, section_id, answer_text, score) VALUES (8, 3, '답변1', 1);
insert into answer (question_id, section_id, answer_text, score) VALUES (8, 3, '답변2', 2);
insert into answer (question_id, section_id, answer_text, score) VALUES (8, 3, '답변3', 3);
insert into answer (question_id, section_id, answer_text, score) VALUES (8, 3, '답변4', 4);
insert into answer (question_id, section_id, answer_text, score) VALUES (9, 3, '답변1', 1);
insert into answer (question_id, section_id, answer_text, score) VALUES (9, 3, '답변2', 2);
insert into answer (question_id, section_id, answer_text, score) VALUES (9, 3, '답변3', 3);
insert into answer (question_id, section_id, answer_text, score) VALUES (9, 3, '답변4', 4);
insert into user_answer (user_id, answer_id) VALUES (1, 4);
insert into user_answer (user_id, answer_id) VALUES (1, 8);
insert into user_answer (user_id, answer_id) VALUES (1, 12);
insert into user_answer (user_id, answer_id) VALUES (1, 13);
insert into user_answer (user_id, answer_id) VALUES (1, 18);
insert into user_answer (user_id, answer_id) VALUES (1, 22);
insert into user_answer (user_id, answer_id) VALUES (1, 26);
insert into user_answer (user_id, answer_id) VALUES (1, 32);
insert into user_answer (user_id, answer_id) VALUES (1, 36);
